# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Leo Xin's Blog
subtitle: Quick notes
description: 惶者生存，偏执者成功
keywords:
author: Leo
# language: zh-Hans
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: https://xinlc.github.io
url: https://xinlichao.cn
root: /
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
  - ".DS_Store"
ignore: 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/xinlc/xinlc.github.io
  branch: master


# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
  hexo-generator-feed
  hexo-generator-search

# 搜索
## Docs: http://theme-next.iissnan.com/third-party-services.html#algolia-search
## https://www.algolia.com/explorer#?index=xinlc
algolia:
  applicationID: '3ZZ8ITB7HE'
  apiKey: '062eb5a54afbcbf3f20452d58fc40035'
  indexName: 'xinlc'
  chunkSize: 5000

# 站内搜索打开
search:
  path: search.xml
  field: post
  content: true
  format: html

#=================
# 主题配置
#=================

theme_config:
  favicon:
    small: /favicon.ico
    medium: /favicon.ico
    apple_touch_icon: /favicon.ico
    safari_pinned_tab: /favicon.ico

  menu_settings:
    icons: true
    badges: true
  menu:
    home: / || fa fa-home
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive

  scheme: Muse
  # scheme: Mist
  # scheme: Pisces
  # scheme: Gemini

  # darkmode: true

  # 头像
  avatar:
    # Replace the default image and set the url here.
    url: https://avatars3.githubusercontent.com/u/18113256?v=3&s=460
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: true

  social:
    GitHub: https://github.com/xinlc || fab fa-github
    Twitter: https://twitter.com/xinlc || fab fa-twitter

  footer:
    since: 2016
    powered: false

  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true

  baidu_analytics: 4530ac9d0bc4e258535c4a9b17029f0c

  # 阅读统计
  ## https://leancloud.cn
  leancloud_visitors:
    enable: false
    app_id: 4WVKPOy2dQ2q5HU2VIoikqvh-gzGzoHsz
    app_key: wWAQMskCxdMIC6KzM6b6hNLq
    server_url: # <your server url>
    security: true

  algolia_search:
    enable: true
    hits:
      per_page: 10
    # labels:
    #   input_placeholder: Search for Posts
    #   hits_empty: "We didn't find any results for the search: ${query}"
    #   hits_stats: "${hits} results found in ${time} ms"
    labels:
      input_placeholder: 搜索
      hits_empty: "未发现与「${query}」相关的内容"
      hits_stats: "${hits} 条相关条目，使用了 ${time} 毫秒"

  # Blog rolls
  links_settings:
    icon: fa fa-link
    title: Links
    # Available values: block | inline
    layout: block
  links:
    W3Cschool: https://www.w3cschool.cn/
    菜鸟教程: http://www.runoob.com
    CTOLib: http://www.ctolib.com
    阿里妈妈: http://mux.alimama.com
    美团技术: https://tech.meituan.com
    segmentfault: https://segmentfault.com
    资源库: http://www.dowebok.com
    Learn X in Y minutes: https://learnxinyminutes.com
    知识库: http://lib.csdn.net/home
    V2EX: https://www.v2ex.com
    前端网址: http://caibaojian.com/links
    博客墙: http://blogwall.us
    awesomes: https://www.awesomes.cn/
    醉牛前端: http://f2er.club/
    粉丝日志: http://blog.fens.me
    极客教程: https://www.geekjc.com
    justjavac: http://justjavac.com
    阮一峰: http://www.ruanyifeng.com/blog/
    廖雪峰: https://www.liaoxuefeng.com
    Linxu运营笔记: https://blog.linuxeye.cn
    caniuse/工具: https://caniuse.com
    css检索: http://cssvalues.com/
    短连接生成: https://git.io
    css88/doc: http://www.css88.com/nav/
    OverAPI/api: http://overapi.com/
    DevDocs/api: http://devdocs.io/
    JS花园/js语法: http://www.jb51.net/onlineread/JavaScript-Garden-CN/#intro
    在线工具/索引: http://tool.oschina.net/
    ToolBox: http://tool.lu/
    设计导航: http://hao.shejidaren.com/
    JSbin/环境: http://jsbin.com/
    RunJs/环境: http://runjs.cn/
    codepen: https://codepen.io